import generateCSS from '../../../assets/js/blocks/generateCss';
import generateCSSUnit from '../../../assets/js/blocks/generateCssUnit';
import hexToRgba from "hex-to-rgba";

function styling(props) {
    const {
        block_id,
        classMigrate,
        fadeHeight,
        fadeHeightTablet,
        fadeHeightMobile,
        boxMarginType,
        boxMarginTop,
        boxMarginRight,
        boxMarginBottom,
        boxMarginLeft,
        boxMarginTopTablet,
        boxMarginRightTablet,
        boxMarginBottomTablet,
        boxMarginLeftTablet,
        boxMarginTopMobile,
        boxMarginRightMobile,
        boxMarginBottomMobile,
        boxMarginLeftMobile,
        boxPaddingTop,
        boxPaddingRight,
        boxPaddingBottom,
        boxPaddingLeft,
        boxPaddingTopTablet,
        boxPaddingRightTablet,
        boxPaddingBottomTablet,
        boxPaddingLeftTablet,
        boxPaddingTopMobile,
        boxPaddingRightMobile,
        boxPaddingBottomMobile,
        boxPaddingLeftMobile,
        boxPaddingType,
        boxMarginTypeH,
        boxMarginTopH,
        boxMarginRightH,
        boxMarginBottomH,
        boxMarginLeftH,
        boxMarginTopTabletH,
        boxMarginRightTabletH,
        boxMarginBottomTabletH,
        boxMarginLeftTabletH,
        boxMarginTopMobileH,
        boxMarginRightMobileH,
        boxMarginBottomMobileH,
        boxMarginLeftMobileH,
        boxPaddingTopH,
        boxPaddingRightH,
        boxPaddingBottomH,
        boxPaddingLeftH,
        boxPaddingTopTabletH,
        boxPaddingRightTabletH,
        boxPaddingBottomTabletH,
        boxPaddingLeftTabletH,
        boxPaddingTopMobileH,
        boxPaddingRightMobileH,
        boxPaddingBottomMobileH,
        boxPaddingLeftMobileH,
        boxPaddingTypeH,
        boxBackgroundColorH,
        boxOpacityH,
        boxBackgroundImgH,
        boxBackgroundPositionH,
        boxBackgroundRepeatH,
        boxBackgroundSizeH,
        boxFixedH,
        boxBorderTypeH,
        boxBorderTopH,
        boxBorderRightH,
        boxBorderBottomH,
        boxBorderLeftH,
        boxBorderColorH,
        boxBorderRadiusH,
        boxShadowColorH,
        boxShadowBlurH,
        boxShadowHorizontalH,
        boxShadowVerticalH,
        boxShadowPositionH,
        titleSizeUnit,
        titleSize,
        titleSizeMobile,
        titleSizeTablet,
        titleMarginType,
        titleMarginTop,
        titleMarginRight,
        titleMarginBottom,
        titleMarginLeft,
        titleMarginTopTablet,
        titleMarginRightTablet,
        titleMarginBottomTablet,
        titleMarginLeftTablet,
        titleMarginTopMobile,
        titleMarginRightMobile,
        titleMarginBottomMobile,
        titleMarginLeftMobile,
        titlePaddingTop,
        titlePaddingRight,
        titlePaddingBottom,
        titlePaddingLeft,
        titlePaddingTopTablet,
        titlePaddingRightTablet,
        titlePaddingBottomTablet,
        titlePaddingLeftTablet,
        titlePaddingTopMobile,
        titlePaddingRightMobile,
        titlePaddingBottomMobile,
        titlePaddingLeftMobile,
        titlePaddingType,
        contentSizeType,
        contentSize,
        contentSizeMobile,
        contentSizeTablet,
        contentMarginType,
        contentMarginTop,
        contentMarginRight,
        contentMarginBottom,
        contentMarginLeft,
        contentMarginTopTablet,
        contentMarginRightTablet,
        contentMarginBottomTablet,
        contentMarginLeftTablet,
        contentMarginTopMobile,
        contentMarginRightMobile,
        contentMarginBottomMobile,
        contentMarginLeftMobile,
        contentPaddingTop,
        contentPaddingRight,
        contentPaddingBottom,
        contentPaddingLeft,
        contentPaddingTopTablet,
        contentPaddingRightTablet,
        contentPaddingBottomTablet,
        contentPaddingLeftTablet,
        contentPaddingTopMobile,
        contentPaddingRightMobile,
        contentPaddingBottomMobile,
        contentPaddingLeftMobile,
        contentPaddingType,
        btnSizeUnit,
        btnSize,
        btnSizeTablet,
        btnSizeMobile,
        btnMarginType,
        btnMarginTop,
        btnMarginRight,
        btnMarginBottom,
        btnMarginLeft,
        btnMarginTopTablet,
        btnMarginRightTablet,
        btnMarginBottomTablet,
        btnMarginLeftTablet,
        btnMarginTopMobile,
        btnMarginRightMobile,
        btnMarginBottomMobile,
        btnMarginLeftMobile,
        btnPaddingTop,
        btnPaddingRight,
        btnPaddingBottom,
        btnPaddingLeft,
        btnPaddingTopTablet,
        btnPaddingRightTablet,
        btnPaddingBottomTablet,
        btnPaddingLeftTablet,
        btnPaddingTopMobile,
        btnPaddingRightMobile,
        btnPaddingBottomMobile,
        btnPaddingLeftMobile,
        btnPaddingType,
        fadePaddingTop,
        fadePaddingRight,
        fadePaddingBottom,
        fadePaddingLeft,
        fadePaddingTopTablet,
        fadePaddingRightTablet,
        fadePaddingBottomTablet,
        fadePaddingLeftTablet,
        fadePaddingTopMobile,
        fadePaddingRightMobile,
        fadePaddingBottomMobile,
        fadePaddingLeftMobile,
        fadePaddingType,
    } = props.attributes

    var selectors = {}
    var tablet_selectors = {}
    var mobile_selectors = {}

    selectors = {
        " .premium-unfold-container": {
            "padding-top": generateCSSUnit(boxPaddingTop, boxPaddingType),
            "padding-right": generateCSSUnit(boxPaddingRight, boxPaddingType),
            "padding-bottom": generateCSSUnit(boxPaddingBottom, boxPaddingType),
            "padding-left": generateCSSUnit(boxPaddingLeft, boxPaddingType),
            "margin-top": generateCSSUnit(boxMarginTop, boxMarginType),
            "margin-right": generateCSSUnit(boxMarginRight, boxMarginType),
            "margin-bottom": generateCSSUnit(boxMarginBottom, boxMarginType),
            "margin-left": generateCSSUnit(boxMarginLeft, boxMarginType),
        },
        " .premium-unfold-container:hover": {
            // "background-color": boxBackgroundColorH ? hexToRgba(boxBackgroundColorH, boxOpacityH) : `none` + "!important",
            // "background-image": boxBackgroundImgH ? `url(${boxBackgroundImgH})` : "none" + "!important",
            // "background-size": boxBackgroundSizeH,
            // "background-position": boxBackgroundPositionH,
            // "background-repeat": boxBackgroundRepeatH,
            // "background-attachment": boxFixedH ? "fixed" : "unset",
            // "border-style": boxBorderTypeH,
            // "border-width": `${boxBorderTopH}px ${boxBorderRightH}px ${boxBorderBottomH}px ${boxBorderLeftH}px`,
            // "border-color": boxBorderColorH,
            // "border-radius": boxBorderRadiusH,
            // "box-shadow": `${boxShadowHorizontalH}px ${boxShadowVerticalH}px ${boxShadowBlurH}px ${boxShadowColorH} ${boxShadowPositionH}`,
            "padding-top": generateCSSUnit(boxPaddingTopH, boxPaddingTypeH),
            "padding-right": generateCSSUnit(boxPaddingRightH, boxPaddingTypeH),
            "padding-bottom": generateCSSUnit(boxPaddingBottomH, boxPaddingTypeH),
            "padding-left": generateCSSUnit(boxPaddingLeftH, boxPaddingTypeH),
            "margin-top": generateCSSUnit(boxMarginTopH, boxMarginTypeH),
            "margin-right": generateCSSUnit(boxMarginRightH, boxMarginTypeH),
            "margin-bottom": generateCSSUnit(boxMarginBottomH, boxMarginTypeH),
            "margin-left": generateCSSUnit(boxMarginLeftH, boxMarginTypeH),
        },
        " .premium-unfold-heading": {
            "font-size": generateCSSUnit(titleSize, titleSizeUnit),
            "padding-top": generateCSSUnit(titlePaddingTop, titlePaddingType),
            "padding-right": generateCSSUnit(titlePaddingRight, titlePaddingType),
            "padding-bottom": generateCSSUnit(titlePaddingBottom, titlePaddingType),
            "padding-left": generateCSSUnit(titlePaddingLeft, titlePaddingType),
            "margin-top": generateCSSUnit(titleMarginTop, titleMarginType),
            "margin-right": generateCSSUnit(titleMarginRight, titleMarginType),
            "margin-bottom": generateCSSUnit(titleMarginBottom, titleMarginType),
            "margin-left": generateCSSUnit(titleMarginLeft, titleMarginType),

        },
        " .premium-unfold-content ": {
            "font-size": generateCSSUnit(contentSize, contentSizeType),
            "padding-top": generateCSSUnit(contentPaddingTop, contentPaddingType),
            "padding-right": generateCSSUnit(contentPaddingRight, contentPaddingType),
            "padding-bottom": generateCSSUnit(contentPaddingBottom, contentPaddingType),
            "padding-left": generateCSSUnit(contentPaddingLeft, contentPaddingType),
            "margin-top": generateCSSUnit(contentMarginTop, contentMarginType),
            "margin-right": generateCSSUnit(contentMarginRight, contentMarginType),
            "margin-bottom": generateCSSUnit(contentMarginBottom, contentMarginType),
            "margin-left": generateCSSUnit(contentMarginLeft, contentMarginType),
        },
        " .premium-unfold-gradient ": {
            "height": generateCSSUnit(fadeHeight, 'px'),
            "padding-top": generateCSSUnit(fadePaddingTop, fadePaddingType),
            "padding-right": generateCSSUnit(fadePaddingRight, fadePaddingType),
            "padding-bottom": generateCSSUnit(fadePaddingBottom, fadePaddingType),
            "padding-left": generateCSSUnit(fadePaddingLeft, fadePaddingType),
        },
        " .premium-button": {
            "font-size": generateCSSUnit(btnSize, btnSizeUnit),
            "padding-top": generateCSSUnit(btnPaddingTop, btnPaddingType),
            "padding-right": generateCSSUnit(btnPaddingRight, btnPaddingType),
            "padding-bottom": generateCSSUnit(btnPaddingBottom, btnPaddingType),
            "padding-left": generateCSSUnit(btnPaddingLeft, btnPaddingType),
            "margin-top": generateCSSUnit(btnMarginTop, btnMarginType),
            "margin-right": generateCSSUnit(btnMarginRight, btnMarginType),
            "margin-bottom": generateCSSUnit(btnMarginBottom, btnMarginType),
            "margin-left": generateCSSUnit(btnMarginLeft, btnMarginType),
        }
    }

    tablet_selectors = {
        " .premium-unfold-container": {
            "padding-top": generateCSSUnit(boxPaddingTopTablet, boxPaddingType),
            "padding-right": generateCSSUnit(boxPaddingRightTablet, boxPaddingType),
            "padding-bottom": generateCSSUnit(boxPaddingBottomTablet, boxPaddingType),
            "padding-left": generateCSSUnit(boxPaddingLeftTablet, boxPaddingType),
            "margin-top": generateCSSUnit(boxMarginTopTablet, boxMarginType),
            "margin-right": generateCSSUnit(boxMarginRightTablet, boxMarginType),
            "margin-bottom": generateCSSUnit(boxMarginBottomTablet, boxMarginType),
            "margin-left": generateCSSUnit(boxMarginLeftTablet, boxMarginType),
        },
        " .premium-unfold-container:hover": {

            "padding-top": generateCSSUnit(boxPaddingTopTabletH, boxPaddingTypeH),
            "padding-right": generateCSSUnit(boxPaddingRightTabletH, boxPaddingTypeH),
            "padding-bottom": generateCSSUnit(boxPaddingBottomTabletH, boxPaddingTypeH),
            "padding-left": generateCSSUnit(boxPaddingLeftTabletH, boxPaddingTypeH),
            "margin-top": generateCSSUnit(boxMarginTopTabletH, boxMarginTypeH),
            "margin-right": generateCSSUnit(boxMarginRightTabletH, boxMarginTypeH),
            "margin-bottom": generateCSSUnit(boxMarginBottomTabletH, boxMarginTypeH),
            "margin-left": generateCSSUnit(boxMarginLeftTabletH, boxMarginTypeH),
        },
        " .premium-unfold-heading": {
            "font-size": generateCSSUnit(titleSizeTablet, titleSizeUnit),
            "padding-top": generateCSSUnit(titlePaddingTopTablet, titlePaddingType),
            "padding-right": generateCSSUnit(titlePaddingRightTablet, titlePaddingType),
            "padding-bottom": generateCSSUnit(titlePaddingBottomTablet, titlePaddingType),
            "padding-left": generateCSSUnit(titlePaddingLeftTablet, titlePaddingType),
            "margin-top": generateCSSUnit(titleMarginTopTablet, titleMarginType),
            "margin-right": generateCSSUnit(titleMarginRightTablet, titleMarginType),
            "margin-bottom": generateCSSUnit(titleMarginBottomTablet, titleMarginType),
            "margin-left": generateCSSUnit(titleMarginLeftTablet, titleMarginType),

        },
        " .premium-unfold-content ": {
            "font-size": generateCSSUnit(contentSizeTablet, contentSizeType),
            "padding-top": generateCSSUnit(contentPaddingTopTablet, contentPaddingType),
            "padding-right": generateCSSUnit(contentPaddingRightTablet, contentPaddingType),
            "padding-bottom": generateCSSUnit(contentPaddingBottomTablet, contentPaddingType),
            "padding-left": generateCSSUnit(contentPaddingLeftTablet, contentPaddingType),
            "margin-top": generateCSSUnit(contentMarginTopTablet, contentMarginType),
            "margin-right": generateCSSUnit(contentMarginRightTablet, contentMarginType),
            "margin-bottom": generateCSSUnit(contentMarginBottomTablet, contentMarginType),
            "margin-left": generateCSSUnit(contentMarginLeftTablet, contentMarginType),
        },
        " .premium-unfold-gradient ": {
            "height": generateCSSUnit(fadeHeightTablet, 'px'),
            "padding-top": generateCSSUnit(fadePaddingTopTablet, fadePaddingType),
            "padding-right": generateCSSUnit(fadePaddingRightTablet, fadePaddingType),
            "padding-bottom": generateCSSUnit(fadePaddingBottomTablet, fadePaddingType),
            "padding-left": generateCSSUnit(fadePaddingLeftTablet, fadePaddingType),
        },
        " .premium-button": {
            "font-size": generateCSSUnit(btnSizeTablet, btnSizeUnit),
            "padding-top": generateCSSUnit(btnPaddingTopTablet, btnPaddingType),
            "padding-right": generateCSSUnit(btnPaddingRightTablet, btnPaddingType),
            "padding-bottom": generateCSSUnit(btnPaddingBottomTablet, btnPaddingType),
            "padding-left": generateCSSUnit(btnPaddingLeftTablet, btnPaddingType),
            "margin-top": generateCSSUnit(btnMarginTopTablet, btnMarginType),
            "margin-right": generateCSSUnit(btnMarginRightTablet, btnMarginType),
            "margin-bottom": generateCSSUnit(btnMarginBottomTablet, btnMarginType),
            "margin-left": generateCSSUnit(btnMarginLeftTablet, btnMarginType),
        }
    }

    mobile_selectors = {
        " .premium-unfold-container": {
            "padding-top": generateCSSUnit(boxPaddingTopMobile, boxPaddingType),
            "padding-right": generateCSSUnit(boxPaddingRightMobile, boxPaddingType),
            "padding-bottom": generateCSSUnit(boxPaddingBottomMobile, boxPaddingType),
            "padding-left": generateCSSUnit(boxPaddingLeftMobile, boxPaddingType),
            "margin-top": generateCSSUnit(boxMarginTopMobile, boxMarginType),
            "margin-right": generateCSSUnit(boxMarginRightMobile, boxMarginType),
            "margin-bottom": generateCSSUnit(boxMarginBottomMobile, boxMarginType),
            "margin-left": generateCSSUnit(boxMarginLeftMobile, boxMarginType),
        },
        " .premium-unfold-container:hover": {
            "padding-top": generateCSSUnit(boxPaddingTopMobileH, boxPaddingTypeH),
            "padding-right": generateCSSUnit(boxPaddingRightMobileH, boxPaddingTypeH),
            "padding-bottom": generateCSSUnit(boxPaddingBottomMobileH, boxPaddingTypeH),
            "padding-left": generateCSSUnit(boxPaddingLeftMobileH, boxPaddingTypeH),
            "margin-top": generateCSSUnit(boxMarginTopMobileH, boxMarginTypeH),
            "margin-right": generateCSSUnit(boxMarginRightMobileH, boxMarginTypeH),
            "margin-bottom": generateCSSUnit(boxMarginBottomMobileH, boxMarginTypeH),
            "margin-left": generateCSSUnit(boxMarginLeftMobileH, boxMarginTypeH),
        },
        " .premium-unfold-heading": {
            "font-size": generateCSSUnit(titleSizeMobile, titleSizeUnit),
            "padding-top": generateCSSUnit(titlePaddingTopMobile, titlePaddingType),
            "padding-right": generateCSSUnit(titlePaddingRightMobile, titlePaddingType),
            "padding-bottom": generateCSSUnit(titlePaddingBottomMobile, titlePaddingType),
            "padding-left": generateCSSUnit(titlePaddingLeftMobile, titlePaddingType),
            "margin-top": generateCSSUnit(titleMarginTopMobile, titleMarginType),
            "margin-right": generateCSSUnit(titleMarginRightMobile, titleMarginType),
            "margin-bottom": generateCSSUnit(titleMarginBottomMobile, titleMarginType),
            "margin-left": generateCSSUnit(titleMarginLeftMobile, titleMarginType),
        },
        " .premium-unfold-content ": {
            "font-size": generateCSSUnit(contentSizeMobile, contentSizeType),
            "padding-top": generateCSSUnit(contentPaddingTopMobile, contentPaddingType),
            "padding-right": generateCSSUnit(contentPaddingRightMobile, contentPaddingType),
            "padding-bottom": generateCSSUnit(contentPaddingBottomMobile, contentPaddingType),
            "padding-left": generateCSSUnit(contentPaddingLeftMobile, contentPaddingType),
            "margin-top": generateCSSUnit(contentMarginTopMobile, contentMarginType),
            "margin-right": generateCSSUnit(contentMarginRightMobile, contentMarginType),
            "margin-bottom": generateCSSUnit(contentMarginBottomMobile, contentMarginType),
            "margin-left": generateCSSUnit(contentMarginLeftMobile, contentMarginType),
        },
        " .premium-unfold-gradient ": {
            "height": generateCSSUnit(fadeHeightMobile, 'px'),
            "padding-top": generateCSSUnit(fadePaddingTopMobile, fadePaddingType),
            "padding-right": generateCSSUnit(fadePaddingRightMobile, fadePaddingType),
            "padding-bottom": generateCSSUnit(fadePaddingBottomMobile, fadePaddingType),
            "padding-left": generateCSSUnit(fadePaddingLeftMobile, fadePaddingType),
        },
        " .premium-button": {
            "font-size": generateCSSUnit(btnSizeMobile, btnSizeUnit),
            "padding-top": generateCSSUnit(btnPaddingTopMobile, btnPaddingType),
            "padding-right": generateCSSUnit(btnPaddingRightMobile, btnPaddingType),
            "padding-bottom": generateCSSUnit(btnPaddingBottomMobile, btnPaddingType),
            "padding-left": generateCSSUnit(btnPaddingLeftMobile, btnPaddingType),
            "margin-top": generateCSSUnit(btnMarginTopMobile, btnMarginType),
            "margin-right": generateCSSUnit(btnMarginRightMobile, btnMarginType),
            "margin-bottom": generateCSSUnit(btnMarginBottomMobile, btnMarginType),
            "margin-left": generateCSSUnit(btnMarginLeftMobile, btnMarginType),
        }
    }

    var styling_css = ""
    var id = `#premium-unfold-${block_id}`
    if (classMigrate) {
        id = `.premium-unfold-${block_id}`
    }

    styling_css = generateCSS(selectors, id)
    styling_css += generateCSS(tablet_selectors, id, true, "tablet")

    styling_css += generateCSS(mobile_selectors, id, true, "mobile")


    return styling_css


}
export default styling