<?php
/**
 * PBG_Blocks_Config.
 *
 * @package PBG
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! class_exists( 'PBG_Blocks_Config' ) ) {

	/**
	 * Class PBG_Blocks_Config.
	 */
	class PBG_Blocks_Config {

		/**
		 * Block Attributes
		 *
		 * @var block_attributes
		 */
		public static $block_attributes = null;

		/**
		 * Block Assets
		 *
		 * @var block_attributes
		 */
		public static $block_assets = null;

		/**
		 * Get Widget List.
		 *
		 * @since 1.8.2
		 *
		 * @return array blocks attributes.
		 */
		public static function get_block_attributes() {

			if ( null === self::$block_attributes ) {

				self::$block_attributes = array(
					'premium/fancy-text'     => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'classMigrate'            => false,
							'align'                   => 'center',
							'block_id'                => '',
							'fancyTextColor'          => '#6ec1e4',
							'fancyTextfontSize'       => '20',
							'fancyTextfontSizeMobile' => '20',
							'fancyTextfontSizeTablet' => '20',
							'fancyTextfontSizeUnit'   => 'px',
							'fancyTextWeight'         => '600',
							'fancyTextUpper'          => false,
							'fancyTextStyle'          => '',
							'fancyTextLetter'         => '',
							'fancyTextBGColor'        => '',
							'shadowColor'             => '',
							'shadowBlur'              => '1',
							'shadowHorizontal'        => '1',
							'shadowVertical'          => '1',
							'cursorColor'             => '#6ec1e4',
							'textColor'               => '#54595f',
							'textfontSize'            => '20',
							'textfontSizeMobile'      => '20',
							'textfontSizeTablet'      => '20',
							'textfontSizeUnit'        => 'px',
							'textWeight'              => '600',
							'textLetter'              => '',
							'textUpper'               => false,
							'textStyle'               => '',
							'textBGColor'             => '',
							'fancyTextBGOpacity'      => '1',
							'textBGOpacity'           => '1',
						),
					),
					'premium/accordion'      => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'titleSize'       => '20',
							'titleSizeUnit'   => 'px',
							'titleSizeTablet' => '20',
							'titleSizeMobile' => '20',
							'descSize'        => '20',
							'descSizeTablet'  => '20',
							'descSizeMobile'  => '20',
							'descSizeUnit'    => 'px',
							'classMigrate'    => false,
						),
					),
					'premium/banner'         => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'classMigrate'    => false,
							'descSize'        => '20',
							'descSizeTablet'  => '20',
							'descSizeMobile'  => '20',
							'descSizeUnit'    => 'px',
							'titleSize'       => '20',
							'titleSizeUnit'   => 'px',
							'titleSizeTablet' => '20',
							'titleSizeMobile' => '20',
							'block_id'        => '',
						),
					),
					'premium/button'         => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'classMigrate'   => false,
							'textSize'       => '20',
							'textSizeTablet' => '20',
							'textSizeMobile' => '20',
							'textSizeUnit'   => 'px',
							'block_id'       => '',
						),
					),
					'premium/countup'        => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'         => '',
							'classMigrate'     => false,
							'numberSize'       => '20',
							'numberSizeTablet' => '20',
							'numberSizeMobile' => '20',
							'numberSizeUnit'   => 'px',
							'prefixSize'       => '20',
							'prefixSizeTablet' => '20',
							'prefixSizeMobile' => '20',
							'prefixSizeUnit'   => 'px',
							'suffixSize'       => '20',
							'suffixSizeTablet' => '20',
							'suffixSizeMobile' => '20',
							'suffixSizeUnit'   => 'px',
							'titleSize'        => '20',
							'titleSizeTablet'  => '20',
							'titleSizeMobile'  => '20',
							'titleSizeUnit'    => 'px',
						),
					),
					'premium/dheading-block' => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'         => '',
							'classMigrate'     => false,
							'firstSize'        => '20',
							'firstSizeTablet'  => '20',
							'firstSizeMobile'  => '20',
							'firstSizeUnit'    => 'px',
							'secondSize'       => '20',
							'secondSizeTablet' => '20',
							'secondSizeMobile' => '20',
							'secondSizeUnit'   => 'px',
						),
					),
					'premium/icon-box'       => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'                 => '',
							'classMigrate'             => false,
							'titleSize'                => '20',
							'titleSizeTablet'          => '20',
							'titleSizeMobile'          => '20',
							'titleSizeUnit'            => 'px',
							'descSize'                 => '20',
							'descSizeTablet'           => '20',
							'descSizeMobile'           => '20',
							'descSizeUnit'             => 'px',
							'btnSize'                  => '20',
							'btnSizeTablet'            => '20',
							'btnSizeMobile'            => '20',
							'btnSizeUnit'              => 'px',
							'iconMarginType'           => 'px',
							'iconMarginTypeH'          => 'px',
							'iconMarginTop'            => '0',
							'iconMarginTopH'           => '0',
							'iconMarginTopTablet'      => '0',
							'iconMarginTopTabletH'     => '0',
							'iconMarginTopMobile'      => '0',
							'iconMarginTopMobileH'     => '0',
							'iconMarginRight'          => '0',
							'iconMarginRightH'         => '0',
							'iconMarginRightTablet'    => '0',
							'iconMarginBottom'         => '0',
							'iconMarginBottomH'        => '0',
							'iconMarginBottomTablet'   => '0',
							'iconMarginBottomTabletH'  => '0',
							'iconMarginBottomMobile'   => '0',
							'iconMarginBottomMobileH'  => '0',
							'iconMarginLeft'           => '0',
							'iconMarginLeftH'          => '0',
							'iconMarginLeftTablet'     => '0',
							'iconMarginLeftTabletH'    => '0',
							'iconMarginLeftMobile'     => '0',
							'iconMarginLeftMobileH'    => '0',
							'iconPaddingType'          => 'px',
							'iconPaddingTypeH'         => 'px',
							'iconPaddingTop'           => '0',
							'iconPaddingTopH'          => '0',
							'iconPaddingTopTablet'     => '0',
							'iconPaddingTopTabletH'    => '0',
							'iconPaddingTopMobile'     => '0',
							'iconPaddingTopMobileH'    => '0',
							'iconPaddingRight'         => '0',
							'iconPaddingRightH'        => '0',
							'iconPaddingRightTablet'   => '0',
							'iconPaddingRightTabletH'  => '0',
							'iconPaddingRightMobile'   => '0',
							'iconPaddingRightMobileH'  => '0',
							'iconPaddingBottom'        => '0',
							'iconPaddingBottomH'       => '0',
							'iconPaddingBottomTablet'  => '0',
							'iconPaddingBottomTabletH' => '0',
							'iconPaddingLeft'          => '0',
							'iconPaddingLeftH'         => '0',
							'iconPaddingLeftTablet'    => '0',
							'iconPaddingLeftTabletH'   => '0',
							'iconPaddingLeftMobile'    => '0',
							'iconPaddingLeftMobileH'   => '0',
							'titleMarginType'          => 'px',
							'titleMarginTop'           => '0',
							'titleMarginRight'         => '0',
							'titleMarginBottom'        => '0',
							'titleMarginLeft'          => '0',
							'titleMarginTopTablet'     => '0',
							'titleMarginRightTablet'   => '0',
							'titleMarginBottomTablet'  => '0',
							'titleMarginLeftTablet'    => '0',
							'titleMarginTopMobile'     => '0',
							'titleMarginRightMobile'   => '0',
							'titleMarginBottomMobile'  => '0',
							'titleMarginLeftMobile'    => '0',
							'titlePaddingTop'          => '0',
							'titlePaddingRight'        => '0',
							'titlePaddingBottom'       => '0',
							'titlePaddingLeft'         => '0',
							'titlePaddingTopTablet'    => '0',
							'titlePaddingRightTablet'  => '0',
							'titlePaddingBottomTablet' => '0',
							'titlePaddingLeftTablet'   => '0',
							'titlePaddingTopMobile'    => '0',
							'titlePaddingRightMobile'  => '0',
							'titlePaddingBottomMobile' => '0',
							'titlePaddingLeftMobile'   => '0',
							'titlePaddingType'         => 'px',
							'labelSizeUnit'            => 'px',
							'labelSize'                => '',
							'labelSizeMobile'          => '',
							'labelSizeTablet'          => '',
							'labelMarginType'          => 'px',
							'labelMarginTop'           => '0',
							'labelMarginRight'         => '0',
							'labelMarginBottom'        => '0',
							'labelMarginLeft'          => '0',
							'labelMarginTopTablet'     => '0',
							'labelMarginRightTablet'   => '0',
							'labelMarginBottomTablet'  => '0',
							'labelMarginLeftTablet'    => '0',
							'labelMarginTopMobile'     => '0',
							'labelMarginRightMobile'   => '0',
							'labelMarginBottomMobile'  => '0',
							'labelMarginLeftMobile'    => '0',
							'descMarginType'           => 'px',
							'descMarginTop'            => '0',
							'descMarginRight'          => '0',
							'descMarginBottom'         => '0',
							'descMarginLeft'           => '0',
							'descMarginTopTablet'      => '0',
							'descMarginRightTablet'    => '0',
							'descMarginBottomTablet'   => '0',
							'descMarginLeftTablet'     => '0',
							'descMarginTopMobile'      => '0',
							'descMarginRightMobile'    => '0',
							'descMarginBottomMobile'   => '0',
							'descMarginLeftMobile'     => '0',
							'descPaddingTop'           => '0',
							'descPaddingRight'         => '0',
							'descPaddingBottom'        => '0',
							'descPaddingLeft'          => '0',
							'descPaddingTopTablet'     => '0',
							'descPaddingRightTablet'   => '0',
							'descPaddingBottomTablet'  => '0',
							'descPaddingLeftTablet'    => '0',
							'descPaddingTopMobile'     => '0',
							'descPaddingRightMobile'   => '0',
							'descPaddingBottomMobile'  => '0',
							'descPaddingLeftMobile'    => '0',
							'descPaddingType'          => 'px',
							'btnMarginType'            => 'px',
							'btnMarginTop'             => '0',
							'btnMarginRight'           => '0',
							'btnMarginBottom'          => '0',
							'btnMarginLeft'            => '0',
							'btnPaddingTop'            => '0',
							'btnPaddingRight'          => '0',
							'btnPaddingBottom'         => '0',
							'btnPaddingLeft'           => '0',
							'btnPaddingTopTablet'      => '0',
							'btnPaddingRightTablet'    => '0',
							'btnPaddingBottomTablet'   => '0',
							'btnPaddingLeftTablet'     => '0',
							'btnPaddingTopMobile'      => '0',
							'btnPaddingRightMobile'    => '0',
							'btnPaddingBottomMobile'   => '0',
							'btnPaddingLeftMobile'     => '0',
							'btnPaddingType'           => '0',
							'btnMarginTypeH'           => 'px',
							'btnMarginTopH'            => '0',
							'btnMarginRightH'          => '0',
							'btnMarginBottomH'         => '0',
							'btnMarginLeftH'           => '0',
							'btnPaddingTopH'           => '0',
							'btnPaddingRightH'         => '0',
							'btnPaddingBottomH'        => '0',
							'btnPaddingLeftH'          => '0',
							'btnPaddingTypeH'          => 'px',
							'marginT'                  => '0',
							'marginR'                  => '0',
							'marginB'                  => '0',
							'marginL'                  => '0',
							'paddingT'                 => '0',
							'paddingR'                 => '0',
							'paddingB'                 => '0',
							'paddingL'                 => '0',
							'paddingU'                 => 'px',
							'marginTTablet'            => '0',
							'marginRTablet'            => '0',
							'marginBTablet'            => '0',
							'marginLTablet'            => '0',
							'marginTMobile'            => '0',
							'marginRMobile'            => '0',
							'marginBMobile'            => '0',
							'marginLMobile'            => '0',
							'paddingTTablet'           => '0',
							'paddingRTablet'           => '0',
							'paddingBTablet'           => '0',
							'paddingLTablet'           => '0',
							'paddingTMobile'           => '0',
							'paddingRMobile'           => '0',
							'paddingBMobile'           => '0',
							'paddingLMobile'           => '0',
							'outerMarginT'             => '0',
							'outerMarginR'             => '0',
							'outerMarginB'             => '0',
							'outerMarginL'             => '0',
							'outerMarginTTablet'       => '0',
							'outerMarginRTablet'       => '0',
							'outerMarginBTablet'       => '0',
							'outerMarginLTablet'       => '0',
							'outerMarginTMobile'       => '0',
							'outerMarginRMobile'       => '0',
							'outerMarginBMobile'       => '0',
							'outerMarginLMobile'       => '0',
							'outerPaddingT'            => '0',
							'outerPaddingR'            => '0',
							'outerPaddingB'            => '0',
							'outerPaddingL'            => '0',
							'outerPaddingTTablet'      => '0',
							'outerPaddingRTablet'      => '0',
							'outerPaddingBTablet'      => '0',
							'outerPaddingLTablet'      => '0',
							'outerPaddingTMobile'      => '0',
							'outerPaddingRMobile'      => '0',
							'outerPaddingBMobile'      => '0',
							'outerPaddingLMobile'      => '0',
							'iconMarginRightTabletH'   => '0',
							'btnMarginTopTablet'       => '0',
							'btnMarginRightTablet'     => '0',
							'btnMarginBottomTablet'    => '0',
							'btnMarginLeftTablet'      => '0',
							'btnMarginTopTabletH'      => '0',
							'btnMarginRightTabletH'    => '0',
							'btnMarginBottomTabletH'   => '0',
							'btnMarginLeftTabletH'     => '0',
							'btnPaddingTopTabletH'     => '0',
							'btnPaddingRightTabletH'   => '0',
							'btnPaddingBottomTabletH'  => '0',
							'btnPaddingLeftTabletH'    => '0',
							'iconMarginRightMobile'    => '0',
							'iconPaddingBottomMobile'  => '0',
							'iconMarginRightMobileH'   => '0',
							'iconPaddingBottomMobileH' => '0',
							'btnMarginTopMobile'       => '0',
							'btnMarginRightMobile'     => '0',
							'btnMarginBottomMobile'    => '0',
							'btnMarginLeftMobile'      => '0',
							'btnMarginTopMobileH'      => '0',
							'btnMarginRightMobileH'    => '0',
							'btnMarginBottomMobileH'   => '0',
							'btnMarginLeftMobileH'     => '0',
							'btnPaddingTopMobileH'     => '0',
							'btnPaddingRightMobileH'   => '0',
							'btnPaddingBottomMobileH'  => '0',
							'btnPaddingLeftMobileH'    => '0',
						),
					),
					'premium/pricing-table'  => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'            => '',
							'classMigrate'        => false,
							'titleSize'           => '20',
							'titleSizeTablet'     => '20',
							'titleSizeMobile'     => '20',
							'titleSizeUnit'       => 'px',
							'descSize'            => '20',
							'descSizeTablet'      => '20',
							'descSizeMobile'      => '20',
							'descSizeUnit'        => 'px',
							'slashSize'           => '20',
							'slashSizeTablet'     => '20',
							'slashSizeMobile'     => '20',
							'slashSizeUnit'       => 'px',
							'currSize'            => '20',
							'currSizeTablet'      => '20',
							'currSizeMobile'      => '20',
							'currSizeUnit'        => 'px',
							'valSize'             => '20',
							'valSizeTablet'       => '20',
							'valSizeMobile'       => '20',
							'valSizeUnit'         => 'px',
							'divSize'             => '20',
							'divSizeTablet'       => '20',
							'divSizeMobile'       => '20',
							'divSizeUnit'         => 'px',
							'durSize'             => '20',
							'durSizeTablet'       => '20',
							'durSizeMobile'       => '20',
							'durSizeUnit'         => 'px',
							'btnSize'             => '20',
							'btnSizeTablet'       => '20',
							'btnSizeMobile'       => '20',
							'btnSizeUnit'         => 'px',
							'badgeTextSize'       => '20',
							'badgeTextSizeTablet' => '20',
							'badgeTextSizeMobile' => '20',
							'badgeTextUnit'       => 'px',
							'listSize'            => '20',
							'listSizeTablet'      => '20',
							'listSizeMobile'      => '20',
							'listSizeUnit'        => 'px',
						),
					),
					'premium/testimonial'    => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'            => '',
							'classMigrate'        => false,
							'authorSize'          => '20',
							'authorSizeTablet'    => '20',
							'authorSizeMobile'    => '20',
							'authorSizeUnit'      => 'px',
							'authorComSize'       => '20',
							'authorComSizeTablet' => '20',
							'authorComSizeMobile' => '20',
							'authorComSizeUnit'   => 'px',
							'bodySize'            => '20',
							'bodySizeTablet'      => '20',
							'bodySizeMobile'      => '20',
							'bodySizeUnit'        => 'px',
						),
					),
					'premium/video-box'      => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'            => '',
							'classMigrate'        => false,
							'videoDescSize'       => '20',
							'videoDescSizeTablet' => '20',
							'videoDescSizeMobile' => '20',
							'videoDescSizeUnit'   => 'px',
						),
					),
					'premium/lottie'         => array(
						'slug'       => '',
						'default'    => true,
						'attributes' => array(
							'block_id'     => '',
							'classMigrate' => false,
							'size'         => '200',
							'sizeUnit'     => 'px',
							'sizeTablet'   => '200',
							'sizeMobile'   => '200',
							'rotate'       => '0',
							'align'        => 'center',
							'backColor'    => '',
							'backOpacity'  => '1',
							'blur'         => '0',
							'bright'       => '100',
							'contrast'     => '100',
							'saturation'   => '100',
							'hue'          => '0',
							'backHColor'   => '',
							'backHOpacity' => '1 ',
							'blurH'        => '0',
							'brightH'      => '100',
							'contrastH'    => '100',
							'saturationH'  => '100',
							'hueH'         => '0',
							'borderType'   => 'none',
							'borderTop'    => '0',
							'borderRight'  => '0',
							'borderBottom' => '0',
							'borderLeft'   => '0',
							'borderColor'  => '',
							'borderRadius' => '0',
							'paddingT'     => '0',
							'paddingR'     => '0',
							'paddingB'     => '0',
							'paddingL'     => '0',
							'paddingU'     => 'px',
							'hideDesktop'  => false,
							'hideTablet'   => false,
							'hideMobile'   => false,
						),
					),
				);

			}

			return self::$block_attributes;
		}
	}
}
