import "./blocks/accordion";
import "./blocks/banner";
import "./blocks/button";
import "./blocks/count-up";
import "./blocks/dual-heading";
import "./blocks/icon";
import "./blocks/icon-box";
import "./blocks/maps";
import "./blocks/pricing-table";
import "./blocks/section";
import "./blocks/testimonials";
import "./blocks/video-box";
import "./blocks/person";
import "./blocks/icon-list"
import "./blocks/content-switcher"
import "./blocks/progress-bar"
//import "./blocks/test";
